# Generated by Django 5.0.1 on 2024-03-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_friendrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'ordering': ('-status',)},
        ),
    ]
